version: '3.8'

services:
  # Customer Database
  customer-db:
    image: mysql:8.0
    container_name: customer-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CUSTOMER_DB_NAME}
      MYSQL_USER: ${CUSTOMER_DB_USER}
      MYSQL_PASSWORD: ${CUSTOMER_DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - scheduling-project-customer-db:/var/lib/mysql
    networks:
      - backend-network
    profiles:
      - databases
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  # Scheduling Database
  scheduling-db:
    image: mysql:8.0
    container_name: scheduling-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SCHEDULING_DB_NAME}
      MYSQL_USER: ${SCHEDULING_DB_USER}
      MYSQL_PASSWORD: ${SCHEDULING_DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - scheduling-project-scheduling-db:/var/lib/mysql
    networks:
      - backend-network
    profiles:
      - databases
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  # User Database
  user-db:
    image: mysql:8.0
    container_name: user-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${USER_DB_NAME}
      MYSQL_USER: ${USER_DB_USER}
      MYSQL_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - scheduling-project-user-db:/var/lib/mysql
    networks:
      - backend-network
    profiles:
      - databases
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

# Rede para comunicação entre os containers
networks:
  backend-network:
    driver: bridge

# Volumes nomeados para persistência de dados
volumes:
  scheduling-project-customer-db:
  scheduling-project-scheduling-db:
  scheduling-project-user-db:
